import type {
  AIRecommendation,
  AIToolSubscription,
  AgentFinding,
  AgentOperationalSummary,
  Approval,
  AuditEvent,
  BusinessMemoryHealth,
  BusinessContextItem,
  ExecutiveBriefItem,
  Organization,
  OrganizationMember,
  RecentBusinessActivity,
  ROIMetrics,
  User,
  WorkflowDefinition,
  WorkflowRun,
} from './types'

export const demoUsers: User[] = [
  { id: 'user-sarah', name: 'Sarah Chen', email: 'sarah@example.com' },
  { id: 'user-omar', name: 'Omar Reyes', email: 'omar@example.com' },
]

export const demoOrganizations: Organization[] = [
  {
    id: 'org-growth-labs',
    name: 'Growth Labs Studio',
    employeeCount: 42,
    primaryProfile: 'DIGITAL_MARKETING_AGENCY',
    secondaryProfiles: ['SEO_CONTENT_AGENCY'],
    createdAt: '2026-08-01T09:00:00.000Z',
  },
  {
    id: 'org-saas-northstar',
    name: 'Northstar SaaS',
    employeeCount: 58,
    primaryProfile: 'B2B_SAAS',
    secondaryProfiles: [],
    createdAt: '2026-08-02T09:00:00.000Z',
  },
]

export const demoMembers: OrganizationMember[] = [
  {
    id: 'mem-sarah-growth',
    organizationId: 'org-growth-labs',
    userId: 'user-sarah',
    role: 'OWNER',
    permissions: [],
  },
  {
    id: 'mem-omar-saas',
    organizationId: 'org-saas-northstar',
    userId: 'user-omar',
    role: 'ADMIN',
    permissions: [],
  },
]

export const demoContextItems: BusinessContextItem[] = [
  {
    id: 'ctx-growth-brand',
    organizationId: 'org-growth-labs',
    domain: 'COMPANY_KNOWLEDGE',
    category: 'BRAND_VOICE',
    title: 'Brand voice',
    content: 'Direct, practical, performance-minded, and clear about evidence behind every recommendation.',
    source: 'Onboarding',
    sourceDate: '2026-08-01',
    confidence: 0.95,
    createdAt: '2026-08-01T10:00:00.000Z',
    humanVerified: true,
    provenance: 'Entered by owner during workspace setup',
  },
  {
    id: 'ctx-growth-icp',
    organizationId: 'org-growth-labs',
    domain: 'COMPANY_KNOWLEDGE',
    category: 'ICP',
    title: 'Best-fit client profile',
    content: 'B2B service companies with 20-150 employees, active paid media, weak conversion tracking, and inconsistent content operations.',
    source: 'Sales playbook',
    sourceDate: '2026-08-04',
    confidence: 0.9,
    createdAt: '2026-08-04T10:00:00.000Z',
    humanVerified: true,
    provenance: 'Imported from sales playbook',
  },
  {
    id: 'ctx-growth-client',
    organizationId: 'org-growth-labs',
    domain: 'OPERATIONAL_CONTEXT',
    category: 'CLIENT_ACCOUNT',
    title: 'Acme Cloud account',
    content: 'Retainer client. Priority KPIs are qualified demo requests, CAC payback, and organic content pipeline.',
    source: 'CRM',
    sourceDate: '2026-08-16',
    confidence: 0.82,
    createdAt: '2026-08-16T12:00:00.000Z',
    expiresAt: '2026-10-16T12:00:00.000Z',
    relatedEntityType: 'client_account',
    relatedEntityId: 'client-acme-cloud',
    humanVerified: false,
    provenance: 'Mock CRM connector',
  },
  {
    id: 'ctx-saas-product',
    organizationId: 'org-saas-northstar',
    domain: 'COMPANY_KNOWLEDGE',
    category: 'PRODUCT',
    title: 'Northstar product summary',
    content: 'Northstar SaaS helps revenue teams track onboarding health, expansion risk, and customer handoff quality.',
    source: 'Product marketing brief',
    sourceDate: '2026-08-03',
    confidence: 0.93,
    createdAt: '2026-08-03T11:00:00.000Z',
    humanVerified: true,
    provenance: 'Imported document',
  },
]

export const workflowTemplates: WorkflowDefinition[] = [
  {
    id: 'tpl-lead-research',
    organizationId: 'template',
    name: 'Lead Research & Qualification',
    description: 'Research a prospect, compare it against ICP, detect duplicates, and prepare an evidence-based fit score.',
    agentType: 'LEAD_RESEARCH',
    trigger: 'MANUAL',
    inputs: [{ key: 'leadUrl', label: 'Prospect website or CRM lead', required: true }],
    steps: [
      { id: 'read-context', name: 'Retrieve business context', description: 'Load ICP, products, CRM hints, and previous findings.', action: 'searchBusinessContext', risk: 'READ' },
      { id: 'research-lead', name: 'Research prospect', description: 'Collect public prospect evidence and CRM duplicate checks.', action: 'researchCompany', risk: 'READ', connectorId: 'web-research' },
      { id: 'score-lead', name: 'Score fit', description: 'Generate structured fit score, risks, evidence, and outreach angle.', action: 'generate lead qualification brief', risk: 'DRAFT' },
      { id: 'approval', name: 'Request next-action approval', description: 'Pause before CRM note or outreach task creation.', action: 'create CRM note', risk: 'APPROVAL_REQUIRED', connectorId: 'crm' },
    ],
    requiredIntegrations: ['CRM', 'Web research'],
    approvalPolicy: { requiredForRisks: ['APPROVAL_REQUIRED'], approverRoles: ['OWNER', 'ADMIN', 'MANAGER'] },
    outputDefinition: {
      leadName: 'string',
      company: 'string',
      fitScore: 'number',
      confidence: 'number',
      reasons: 'string[]',
      evidence: 'string[]',
      likelyNeeds: 'string[]',
      risks: 'string[]',
      recommendedNextAction: 'string',
      suggestedOutreachAngle: 'string',
    },
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: 'tpl-competitor-monitor',
    organizationId: 'template',
    name: 'Competitor / Market Monitoring',
    description: 'Monitor configured competitors and markets, deduplicate known developments, and rank what matters.',
    agentType: 'COMPETITOR_MONITOR',
    trigger: 'SCHEDULED',
    schedule: 'Weekdays 07:00',
    inputs: [{ key: 'competitorSet', label: 'Competitor or market list', required: true }],
    steps: [
      { id: 'load-known', name: 'Load known findings', description: 'Retrieve previous competitor findings with source dates.', action: 'getCompetitorFindings', risk: 'READ' },
      { id: 'research-market', name: 'Research developments', description: 'Use public and connected sources to find material changes.', action: 'researchCompany', risk: 'READ', connectorId: 'web-research' },
      { id: 'rank', name: 'Rank and deduplicate', description: 'Identify opportunity, risk, and recommended response.', action: 'generate market monitoring finding', risk: 'DRAFT' },
    ],
    requiredIntegrations: ['Web research'],
    approvalPolicy: { requiredForRisks: ['APPROVAL_REQUIRED'], approverRoles: ['OWNER', 'ADMIN', 'MANAGER'] },
    outputDefinition: {
      development: 'string',
      competitorOrMarket: 'string',
      importanceScore: 'number',
      whyItMatters: 'string',
      source: 'string',
      sourceDate: 'string',
      opportunity: 'string',
      risk: 'string',
      recommendedResponse: 'string',
    },
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: 'tpl-marketing-content',
    organizationId: 'template',
    name: 'Marketing & Content Workflow',
    description: 'Turn context, market findings, campaign goals, and prior content into briefs and approval-ready drafts.',
    agentType: 'MARKETING_CONTENT',
    trigger: 'MANUAL',
    inputs: [{ key: 'campaignGoal', label: 'Campaign goal', required: true }],
    steps: [
      { id: 'load-brand', name: 'Load brand and context', description: 'Retrieve brand, ICP, products, prior content, and competitor findings.', action: 'searchBusinessContext', risk: 'READ' },
      { id: 'brief', name: 'Create content brief', description: 'Create evidence-backed opportunity and brief.', action: 'draft content brief', risk: 'DRAFT' },
      { id: 'draft', name: 'Create draft', description: 'Draft content in approved tone with sources attached.', action: 'draft content', risk: 'DRAFT' },
      { id: 'publish-approval', name: 'Publication approval', description: 'External publishing cannot happen without approval.', action: 'publish content', risk: 'APPROVAL_REQUIRED', connectorId: 'documents' },
    ],
    requiredIntegrations: ['Documents'],
    approvalPolicy: { requiredForRisks: ['APPROVAL_REQUIRED'], approverRoles: ['OWNER', 'ADMIN', 'MANAGER'] },
    outputDefinition: { opportunity: 'string', brief: 'string', draft: 'string', sources: 'string[]' },
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: 'tpl-weekly-report',
    organizationId: 'template',
    name: 'Weekly Business Reporting',
    description: 'Collect KPIs, compare periods, explain changes, include findings, and recommend next actions.',
    agentType: 'WEEKLY_REPORT',
    trigger: 'SCHEDULED',
    schedule: 'Monday 08:00',
    inputs: [{ key: 'reportingPeriod', label: 'Reporting period', required: true }],
    steps: [
      { id: 'collect-kpis', name: 'Collect KPI inputs', description: 'Read analytics, CRM, workflow, spend, and findings.', action: 'readAnalytics', risk: 'READ', connectorId: 'analytics' },
      { id: 'analyze', name: 'Analyze changes', description: 'Detect anomalies, wins, risks, and likely causes.', action: 'generate weekly report', risk: 'DRAFT' },
      { id: 'approval', name: 'Report approval', description: 'Approval is needed before sending client or executive reports.', action: 'send client report', risk: 'APPROVAL_REQUIRED', connectorId: 'email' },
    ],
    requiredIntegrations: ['Analytics', 'CRM', 'Email'],
    approvalPolicy: { requiredForRisks: ['APPROVAL_REQUIRED'], approverRoles: ['OWNER', 'ADMIN', 'MANAGER'] },
    outputDefinition: {
      reportingPeriod: 'string',
      executiveSummary: 'string',
      KPIChanges: 'string[]',
      wins: 'string[]',
      risks: 'string[]',
      anomalies: 'string[]',
      explanations: 'string[]',
      recommendedActions: 'string[]',
    },
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: 'tpl-executive-brief',
    organizationId: 'template',
    name: 'Executive Daily Brief',
    description: 'Synthesize opportunities, risks, approvals, deadlines, workflow issues, and spend recommendations for management.',
    agentType: 'EXECUTIVE_BRIEF',
    trigger: 'SCHEDULED',
    schedule: 'Weekdays 07:30',
    inputs: [{ key: 'briefDate', label: 'Brief date', required: true }],
    steps: [
      { id: 'collect-signals', name: 'Collect management signals', description: 'Load agent findings, approvals, calendar, workflow failures, and spend recommendations.', action: 'searchBusinessContext', risk: 'READ' },
      { id: 'synthesize', name: 'Synthesize brief', description: 'Produce concise priorities without repeating low-value noise.', action: 'generate executive brief', risk: 'DRAFT' },
    ],
    requiredIntegrations: ['Calendar', 'Workflow engine'],
    approvalPolicy: { requiredForRisks: ['APPROVAL_REQUIRED'], approverRoles: ['OWNER', 'ADMIN', 'MANAGER'] },
    outputDefinition: {
      date: 'string',
      topPriorities: 'string[]',
      opportunities: 'string[]',
      risks: 'string[]',
      pendingDecisions: 'string[]',
      deadlines: 'string[]',
      workflowIssues: 'string[]',
      recommendedActions: 'string[]',
    },
    status: 'ACTIVE',
    version: 1,
  },
]

export const demoWorkflows: WorkflowDefinition[] = workflowTemplates.map((template) => ({
  ...template,
  id: template.id.replace('tpl-', 'wf-growth-'),
  templateId: template.id,
  organizationId: 'org-growth-labs',
  status: template.id === 'tpl-marketing-content' ? 'DRAFT' : 'ACTIVE',
}))

export const demoApprovals: Approval[] = [
  {
    id: 'approval-content-1',
    organizationId: 'org-growth-labs',
    workflowRunId: 'run-weekly-1',
    workflowStepId: 'step-approval',
    agentType: 'WEEKLY_REPORT',
    proposedAction: 'Send weekly performance report to Acme Cloud',
    targetSystem: 'Email',
    affectedEntity: 'client-acme-cloud',
    generatedContent: 'Weekly report draft with KPI changes, campaign wins, and two recommended budget shifts.',
    reason: 'External client report requires management approval.',
    risk: 'APPROVAL_REQUIRED',
    status: 'PENDING',
    createdAt: '2026-08-23T04:15:00.000Z',
  },
]

export const demoRuns: WorkflowRun[] = [
  {
    id: 'run-weekly-1',
    organizationId: 'org-growth-labs',
    workflowId: 'wf-growth-weekly-report',
    status: 'WAITING_FOR_APPROVAL',
    startedAt: '2026-08-23T04:00:00.000Z',
    idempotencyKey: 'wf-growth-weekly-report:2026-W34',
    resultSummary: 'Weekly report drafted and waiting for approval before external delivery.',
    steps: [
      { id: 'run-step-1', workflowRunId: 'run-weekly-1', stepDefinitionId: 'collect-kpis', name: 'Collect KPI inputs', risk: 'READ', status: 'COMPLETED', startedAt: '2026-08-23T04:00:00.000Z', completedAt: '2026-08-23T04:01:00.000Z', outputSummary: 'Analytics, CRM, workflow, spend, and findings retrieved.' },
      { id: 'run-step-2', workflowRunId: 'run-weekly-1', stepDefinitionId: 'analyze', name: 'Analyze changes', risk: 'DRAFT', status: 'COMPLETED', startedAt: '2026-08-23T04:01:00.000Z', completedAt: '2026-08-23T04:04:00.000Z', outputSummary: 'Detected 3 wins, 2 risks, and one campaign anomaly.' },
      { id: 'run-step-3', workflowRunId: 'run-weekly-1', stepDefinitionId: 'approval', name: 'Report approval', risk: 'APPROVAL_REQUIRED', status: 'WAITING_FOR_APPROVAL', startedAt: '2026-08-23T04:04:00.000Z', approvalId: 'approval-content-1', outputSummary: 'Approval requested.' },
    ],
  },
]

export const demoFindings: AgentFinding[] = [
  {
    id: 'finding-lead-1',
    organizationId: 'org-growth-labs',
    agentType: 'LEAD_RESEARCH',
    findingType: 'qualified_lead',
    title: '7 qualified agency prospects',
    content: 'Seven prospects matched ICP with visible paid media activity and weak conversion tracking evidence.',
    source: 'Lead Research & Qualification workflow',
    sourceDate: '2026-08-23',
    confidence: 0.78,
    createdAt: '2026-08-23T03:20:00.000Z',
    expiresAt: '2026-09-06T03:20:00.000Z',
    workflowRunId: 'run-leads-1',
    humanVerified: false,
    status: 'ACTIVE',
  },
  {
    id: 'finding-competitor-1',
    organizationId: 'org-growth-labs',
    agentType: 'COMPETITOR_MONITOR',
    findingType: 'market_development',
    title: 'Competitor launched AI audit landing page',
    content: 'A direct competitor added a public AI stack audit offer. Opportunity: publish differentiated spend-to-workflow positioning.',
    source: 'Competitor Monitor',
    sourceUrl: 'https://example.com',
    sourceDate: '2026-08-22',
    confidence: 0.72,
    createdAt: '2026-08-23T02:10:00.000Z',
    expiresAt: '2026-09-22T02:10:00.000Z',
    humanVerified: false,
    status: 'ACTIVE',
  },
]

export const demoAITools: AIToolSubscription[] = [
  { id: 'tool-writer', organizationId: 'org-growth-labs', toolName: 'Draftly AI', vendor: 'Draftly', category: 'Writing', capability: 'Long-form content', department: 'Marketing', owner: 'Content Lead', monthlyCost: 900, billingCycle: 'MONTHLY', seatsPurchased: 18, activeSeats: 9, renewalDate: '2026-10-15', status: 'APPROVED', usageLevel: 'MEDIUM', notes: 'Possible overlap with AIBeat content workflow.' },
  { id: 'tool-research', organizationId: 'org-growth-labs', toolName: 'ProspectScope', vendor: 'ProspectScope', category: 'Research', capability: 'Lead research', department: 'Sales', owner: 'Sales Ops', monthlyCost: 720, billingCycle: 'MONTHLY', seatsPurchased: 12, activeSeats: 5, renewalDate: '2026-09-30', status: 'APPROVED', usageLevel: 'LOW' },
  { id: 'tool-social', organizationId: 'org-growth-labs', toolName: 'SocialSpark', vendor: 'SocialSpark', category: 'Social AI', capability: 'Social drafts', department: 'Marketing', owner: 'Growth Manager', monthlyCost: 360, billingCycle: 'MONTHLY', seatsPurchased: 8, activeSeats: 4, renewalDate: '2026-11-01', status: 'REVIEWING', usageLevel: 'LOW' },
  { id: 'tool-shadow', organizationId: 'org-growth-labs', toolName: 'Unknown team AI', vendor: 'Unverified', category: 'General AI', capability: 'Unknown', department: 'Mixed', owner: 'Unknown', monthlyCost: 140, billingCycle: 'MONTHLY', seatsPurchased: 4, activeSeats: 4, renewalDate: '2026-09-01', status: 'UNAPPROVED', usageLevel: 'MEDIUM' },
]

export const demoRecommendations: AIRecommendation[] = [
  {
    id: 'rec-consolidate-research',
    organizationId: 'org-growth-labs',
    type: 'CONSOLIDATE',
    title: 'Review potential overlap: ProspectScope + AIBeat Lead Research',
    rationale: 'ProspectScope has 5 active seats out of 12 and overlaps with lead research, CRM duplicate checks, and fit scoring workflow coverage.',
    estimatedMonthlySavings: 420,
    confidence: 0.68,
    relatedToolIds: ['tool-research'],
    relatedAgentType: 'LEAD_RESEARCH',
    relatedWorkflowTemplateId: 'tpl-lead-research',
  },
  {
    id: 'rec-review-social',
    organizationId: 'org-growth-labs',
    type: 'REVIEW',
    title: 'Review low-use social drafting subscription',
    rationale: 'SocialSpark usage is low and may be covered by governed Marketing & Content workflows after brand context is configured.',
    estimatedMonthlySavings: 180,
    confidence: 0.6,
    relatedToolIds: ['tool-social'],
    relatedAgentType: 'MARKETING_CONTENT',
    relatedWorkflowTemplateId: 'tpl-marketing-content',
  },
  {
    id: 'rec-automate-reporting',
    organizationId: 'org-growth-labs',
    type: 'AUTOMATE_WITH_AIBEAT',
    title: 'Automate recurring client reporting effort',
    rationale: 'Weekly client reporting still consumes manual analyst time even though analytics, CRM, findings, and spend data can be summarized by the Weekly Business Reporting workflow.',
    estimatedMonthlySavings: 520,
    confidence: 0.74,
    relatedToolIds: [],
    relatedAgentType: 'WEEKLY_REPORT',
    relatedWorkflowTemplateId: 'tpl-weekly-report',
  },
]

export const demoAuditEvents: AuditEvent[] = [
  { id: 'audit-1', organizationId: 'org-growth-labs', userId: 'user-sarah', workflowId: 'wf-growth-weekly-report', workflowRunId: 'run-weekly-1', stepId: 'run-step-1', tool: 'readAnalytics', action: 'Retrieved analytics', inputSummary: 'Weekly KPI period', outputSummary: 'Analytics rows summarized without raw credentials.', result: 'SUCCESS', timestamp: '2026-08-23T04:01:00.000Z' },
  { id: 'audit-2', organizationId: 'org-growth-labs', agentType: 'WEEKLY_REPORT', workflowId: 'wf-growth-weekly-report', workflowRunId: 'run-weekly-1', stepId: 'run-step-2', action: 'Generated weekly report draft', inputSummary: 'KPI changes, CRM summary, AI spend, findings', outputSummary: 'Draft report generated with confidence and sources.', result: 'SUCCESS', timestamp: '2026-08-23T04:04:00.000Z' },
  { id: 'audit-3', organizationId: 'org-growth-labs', agentType: 'WEEKLY_REPORT', workflowId: 'wf-growth-weekly-report', workflowRunId: 'run-weekly-1', stepId: 'run-step-3', approvalId: 'approval-content-1', action: 'Approval requested', inputSummary: 'External report delivery', outputSummary: 'Workflow blocked pending approval.', result: 'BLOCKED', timestamp: '2026-08-23T04:04:30.000Z' },
]

export const demoRoiMetrics: ROIMetrics = {
  organizationId: 'org-growth-labs',
  aiSpendMonthly: 4680,
  potentialSavingsMonthly: 1120,
  workflowsCompleted: 1284,
  estimatedHoursSaved: 326,
  estimatedSavings: 8420,
  aiToolCost: 387,
  workflowSuccessRate: 97.1,
  approvalRate: 94.2,
  activeWorkflows: 4,
  activeAgents: 5,
}

export const demoExecutiveBriefItems: ExecutiveBriefItem[] = [
  {
    id: 'brief-leads',
    organizationId: 'org-growth-labs',
    type: 'OPPORTUNITY',
    title: '7 qualified prospects discovered',
    summary: 'Lead Research found prospects matching the agency ICP with evidence of paid media activity and weak conversion tracking.',
    href: '/business/agents',
  },
  {
    id: 'brief-competitor',
    organizationId: 'org-growth-labs',
    type: 'RISK',
    title: 'Competitor launched a new AI audit service',
    summary: 'Competitor Monitor flagged a new positioning threat and recommended a differentiated spend-to-workflow response.',
    href: '/business/reports',
  },
  {
    id: 'brief-report-approval',
    organizationId: 'org-growth-labs',
    type: 'APPROVAL',
    title: 'Weekly client report awaiting approval',
    summary: 'Weekly Business Reporting drafted the Acme Cloud report and paused before external delivery.',
    href: '/business/approvals',
  },
]

export const demoBusinessMemoryHealth: BusinessMemoryHealth = {
  organizationId: 'org-growth-labs',
  companyKnowledgeScore: 86,
  operationalContextScore: 71,
  crmStatus: 'CONNECTED',
  analyticsStatus: 'CONNECTED',
  calendarStatus: 'CONNECTED',
  documentCount: 124,
  agentFindingCount: 48,
  lastUpdatedAt: '12 min ago',
}

export const demoAgentSummaries: AgentOperationalSummary[] = [
  {
    agentType: 'LEAD_RESEARCH',
    group: 'INTELLIGENCE',
    status: 'ACTIVE',
    lastRunAt: '2026-08-23T03:20:00.000Z',
    nextRunAt: 'Manual run',
    keyResult: '7 qualified leads found',
  },
  {
    agentType: 'COMPETITOR_MONITOR',
    group: 'INTELLIGENCE',
    status: 'ACTIVE',
    lastRunAt: '2026-08-23T02:10:00.000Z',
    nextRunAt: '2026-08-24T02:00:00.000Z',
    keyResult: '1 high-impact market development detected',
  },
  {
    agentType: 'MARKETING_CONTENT',
    group: 'INTELLIGENCE',
    status: 'DRAFT',
    lastRunAt: '2026-08-22T13:42:00.000Z',
    nextRunAt: 'Manual run',
    keyResult: '2 campaign drafts prepared from brand context',
    pendingOutput: 'Marketing draft awaiting approval',
  },
  {
    agentType: 'WEEKLY_REPORT',
    group: 'REPORTING',
    status: 'WAITING_APPROVAL',
    lastRunAt: '2026-08-23T04:00:00.000Z',
    nextRunAt: '2026-08-24T03:00:00.000Z',
    keyResult: 'Weekly client report drafted',
    pendingOutput: 'Report approval required before delivery',
  },
  {
    agentType: 'EXECUTIVE_BRIEF',
    group: 'EXECUTIVE',
    status: 'ACTIVE',
    lastRunAt: '2026-08-23T02:31:00.000Z',
    nextRunAt: '2026-08-24T02:30:00.000Z',
    keyResult: '3 priority items identified',
  },
]

export const demoRecentActivity: RecentBusinessActivity[] = [
  {
    id: 'activity-leads-complete',
    organizationId: 'org-growth-labs',
    timestampLabel: '08:04',
    title: 'Lead Research completed',
    summary: '7 qualified leads found',
    status: 'SUCCESS',
    href: '/business/agents',
    agentType: 'LEAD_RESEARCH',
  },
  {
    id: 'activity-brief-complete',
    organizationId: 'org-growth-labs',
    timestampLabel: '07:31',
    title: 'Executive Brief completed',
    summary: '3 priority items identified',
    status: 'SUCCESS',
    href: '/business/reports',
    agentType: 'EXECUTIVE_BRIEF',
  },
  {
    id: 'activity-competitor',
    organizationId: 'org-growth-labs',
    timestampLabel: '07:10',
    title: 'Competitor Monitor completed',
    summary: '1 high-impact development detected',
    status: 'NEEDS_ATTENTION',
    href: '/business/reports',
    agentType: 'COMPETITOR_MONITOR',
  },
  {
    id: 'activity-marketing-approval',
    organizationId: 'org-growth-labs',
    timestampLabel: 'Yesterday 16:42',
    title: 'Marketing draft awaiting approval',
    summary: 'Campaign draft paused at the approval boundary',
    status: 'WAITING_APPROVAL',
    href: '/business/approvals',
    agentType: 'MARKETING_CONTENT',
  },
]
