import { getBusinessAIMode, getModelRouter, type ModelRouter } from '../model-router'
import { normalizeLeadUrl } from '../lead-research'
import { buildAssistantPrompt } from './prompt'
import { validateAssistantMessage, validateAssistantResponse } from './validation'
import type { AIBeatAssistantContext, AIBeatAssistantMessage, AIBeatAssistantResponse } from './types'

export async function askAIBeat(input: { question: unknown; context: AIBeatAssistantContext; history?: AIBeatAssistantMessage[]; env?: Readonly<Record<string, string | undefined>>; routerFactory?: () => Promise<ModelRouter> }): Promise<AIBeatAssistantResponse> {
  const question = validateAssistantMessage(input.question); const env = input.env ?? process.env
  if (getBusinessAIMode(env) === 'mock') return mockAssistantResponse(question, input.context)
  const router = await (input.routerFactory ?? (() => getModelRouter(env)))()
  const result = await router.extractStructured<unknown>(buildAssistantPrompt(question, input.context, (input.history ?? []).slice(-10)), 'AIBEAT_ASSISTANT')
  return validateAssistantResponse(result.data, { provider: result.usage.provider, model: result.usage.model, tokensIn: result.usage.tokensIn, tokensOut: result.usage.tokensOut, latencyMs: result.usage.latencyMs })
}

export function mockAssistantResponse(question: string, context: AIBeatAssistantContext): AIBeatAssistantResponse {
  const lower = question.toLowerCase(); const usage = { provider: 'mock', model: 'deterministic-assistant', tokensIn: 0, tokensOut: 0, latencyMs: 0 }
  const domain = extractDomain(question)
  if (domain && /(research|qualify|lead|prospect)/.test(lower)) return { message: `I recommend Lead Research & Qualification for ${domain}. AIBeat will prepare a qualification against Business Memory, but it will not run until you review and start the workflow.`, intent: 'WORKFLOW_PREPARE', suggestions: [{ label: 'Review Lead Research', href: '/business/workflows', workflowId: 'tpl-lead-research', workflowInput: { leadUrl: normalizeLeadUrl(domain) } }, { label: 'Review Business Memory', href: '/business/context' }], missingContext: missingIcp(context), usage }
  if (/(competitor|market monitor)/.test(lower)) return { message: 'Competitor / Market Monitoring is the right specialized workflow. It tracks material developments, deduplicates prior findings, and proposes evidence-backed responses.', intent: 'WORKFLOW_DISCOVERY', suggestions: [{ label: 'Open Competitor Monitoring', href: '/business/workflows', workflowId: 'tpl-competitor-monitor' }, { label: 'Review Integrations', href: '/business/integrations' }], missingContext: context.memoryCategories.some((item) => item.toLowerCase().includes('competitor')) ? [] : ['Competitor list', 'Market positioning'], usage }
  if (/(lead|prospect|sales|more qualified)/.test(lower)) return { message: 'Lead Research & Qualification is the best starting workflow. It compares prospects with your ICP and prepares an evidence-based next action behind approval.', intent: 'WORKFLOW_DISCOVERY', suggestions: [{ label: 'Open Lead Research', href: '/business/workflows', workflowId: 'tpl-lead-research' }, { label: 'Review Business Memory', href: '/business/context' }], missingContext: missingIcp(context), usage }
  if (/(memory|company information|company info|add information|context|missing)/.test(lower)) return { message: 'Business Memory is the shared organization context used by AIBeat workflows. Add your ICP, products, services, positioning, and policies there before relying on recommendations.', intent: 'BUSINESS_MEMORY_HELP', suggestions: [{ label: 'Add Business Memory', href: '/business/context' }], missingContext: missingIcp(context), usage }
  if (/(approval|waiting)/.test(lower)) return { message: `Approvals keep external or sensitive actions under human control. Your workspace currently has ${context.pendingApprovals} pending approval${context.pendingApprovals === 1 ? '' : 's'}.`, intent: 'APPROVAL_HELP', suggestions: [{ label: 'View Approvals', href: '/business/approvals' }, { label: 'View Audit', href: '/business/audit' }], missingContext: [], usage }
  if (/(integrat|connect)/.test(lower)) return { message: 'Integrations connect AIBeat to approved external systems. Review connection status before using workflows that depend on CRM, analytics, documents, or collaboration tools.', intent: 'INTEGRATION_HELP', suggestions: [{ label: 'Connect Integration', href: '/business/integrations' }], missingContext: [], usage }
  if (/(weekly|report)/.test(lower)) return { message: 'Weekly Business Reporting collects KPI signals, explains changes, and prepares a governed report. External delivery remains approval-gated.', intent: 'REPORT_HELP', suggestions: [{ label: 'Open Workflows', href: '/business/workflows', workflowId: 'tpl-weekly-report' }, { label: 'Open Reports', href: '/business/reports' }], missingContext: [], usage }
  if (/(ai stack|model|gemini|runtime)/.test(lower)) return { message: `Your AI runtime is ${context.ai.mode} using ${context.ai.provider}. AI Stack shows its configuration and tool visibility.`, intent: 'AI_STACK_HELP', suggestions: [{ label: 'Open AI Stack', href: '/business/ai-stack' }], missingContext: [], usage }
  if (/(set up|setup|configure first|start first|what should i configure)/.test(lower)) return { message: 'Start with Business Memory: add your ICP, products or services, positioning, and policies. Then connect the integrations needed by your first workflow and review approval roles.', intent: 'GENERAL_BUSINESS_GUIDANCE', suggestions: [{ label: 'Configure Business Memory', href: '/business/context' }, { label: 'Review Integrations', href: '/business/integrations' }, { label: 'Review Settings', href: '/business/settings' }], missingContext: missingIcp(context), usage }
  return { message: 'AIBeat Business helps you run governed workflows for lead research, competitor monitoring, content, reporting, and executive prioritization using shared Business Memory and human approvals.', intent: 'PRODUCT_HELP', suggestions: [{ label: 'Open Dashboard', href: '/business/dashboard' }, { label: 'Explore Workflows', href: '/business/workflows' }, { label: 'Configure Business Memory', href: '/business/context' }], missingContext: missingIcp(context), usage }
}
function extractDomain(value: string) { return value.match(/(?:https?:\/\/)?(?:www\.)?([a-z0-9-]+(?:\.[a-z0-9-]+)+)(?:\/[^\s]*)?/i)?.[0] }
function missingIcp(context: AIBeatAssistantContext) { const categories = context.memoryCategories.map((item) => item.toLowerCase()); return categories.some((item) => item.includes('market') || item.includes('customer')) ? [] : ['Ideal customer profile', 'Target company characteristics'] }
